export { default as HomePage } from './HomePage'
export { default as BookingsPage } from './BookingsPage'
export { default as WalletPage } from './WalletPage'
export { default as ProfilePage } from './ProfilePage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as DestinationDetailPage } from './DestinationDetailPage'
export { default as BookingPage } from './BookingPage'
